const gallery=['show-01.jpeg','show-02.jpeg','show-03.jpeg','show-04.jpeg','show-05.jpeg','show-06.jpeg','show-07.jpeg','show-08.jpeg','show-09.jpeg','show-10.jpeg'];
const copy={zh:{navShows:'近期演出',navGallery:'过往演出',navMembership:'会员',navBenefits:'会员福利',memberLogin:'会员登录'},en:{navShows:'Shows',navGallery:'Past Shows',navMembership:'Membership',navBenefits:'Benefits',memberLogin:'Member Login'}};
let lang=localStorage.getItem('lz_lang')||'zh';
function img(n){return 'assets/gallery/'+n}
function render(){const r=location.hash.replace('#','')||'home';const app=document.getElementById('app'); if(r==='home')app.innerHTML=home(); else if(r==='shows')app.innerHTML=shows(); else if(r==='gallery')app.innerHTML=galleryPage(); else if(r==='membership')app.innerHTML=membership(); else if(r==='benefits')app.innerHTML=benefits(); else if(r==='login')app.innerHTML=login(); else if(r==='admin')app.innerHTML=admin(); else app.innerHTML=home(); wire();}
function home(){return `<section class="hero"><div class="hero-bg" style="background-image:url('assets/hero-home.jpeg')"></div><div class="hero-content"><div class="eyebrow">LOADING ZONE COMEDY · MELBOURNE</div><h1>把好笑的事，<br><em>认真做。</em></h1><p>候场喜剧是一群在墨尔本做中文现场喜剧的人。来看演出，也来成为我们的会员。</p><div class="cta-row"><a class="btn primary" href="#shows">查看近期演出</a><a class="btn" href="#membership">加入会员</a></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">UPCOMING</div><h2>近期演出</h2></div><p>Eventbrite 活动可通过后台自动同步到这里；网站仍可独立编辑中文标题、置顶和首页展示。</p></div>${showCards()}</section><section class="section alt"><div class="section-head"><div><div class="eyebrow">MEMBERSHIP</div><h2>成为候场会员</h2></div><p>一次购买即可成为会员，也可以选择自动续费，让会员福利持续有效。</p></div><div class="membership"><div class="member-panel"><div class="eyebrow">LOADING ZONE MEMBER</div><h3>一张会员卡，<br>把好笑带回生活。</h3><div class="price">$— <small>/ 会员详情待定</small></div><div class="benefit-list"><div>✓ 演出会员专属优惠</div><div>✓ 合作商家福利</div><div>✓ 数字会员卡</div></div><a class="btn primary" href="#membership">查看会员方案</a></div><div class="digital-card"><img src="assets/logo.png"><div><div class="member-no">LZC · MEMBER 000001</div><div class="member-name">示例会员</div><div>ACTIVE MEMBER · 2027.10.08</div></div></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">PAST SHOWS</div><h2>过往演出</h2></div><a class="btn" href="#gallery">浏览 Gallery</a></div><div class="gallery">${gallery.slice(0,6).map((x,i)=>`<figure><img src="${img(x)}"><figcaption>候场喜剧 · Past Show ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div></section>`}
function showCards(){let arr=[['10 OCT','Eventbrite · 近期演出','Eventbrite 活动导入 · 日期 / 场地 / 票务以活动页为准','eventbrite'],['待添加','其他场地演出','后台手动添加 · 可填写票务链接、场地与中文介绍','manual'],['待添加','特别演出 / 联合演出','后台手动添加 · 可设置首页置顶与展示顺序','manual']];return `<div class="cards">${arr.map(s=>`<article class="show-card show-source-card"><div class="show-placeholder ${s[3]}"><span>${s[3]==='eventbrite'?'EVENTBRITE':'MANUAL'}</span></div><div class="show-body"><div class="date">${s[0]}</div><h3>${s[1]}</h3><div class="meta">${s[2]}</div><a class="card-link" href="#shows">查看详情 →</a></div></article>`).join('')}</div>`}
function shows(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">UPCOMING SHOWS</div><h2>近期演出</h2></div><p>Eventbrite 演出自动导入；其他场地或其他售票平台的演出可由后台手动添加。</p></div>${showCards()}</section>`}
function galleryPage(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">GALLERY</div><h2>过往演出</h2></div><p>这里专门展示过往演出照片。你提供的照片全部归入 Past Shows；以后可以继续从后台上传新照片、添加标题并发布。</p></div><div class="gallery">${gallery.map((x,i)=>`<figure><img src="${img(x)}"><figcaption>Past Show ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div></section>`}
function membership(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">MEMBERSHIP</div><h2>候场会员</h2></div><p>墨尔本、悉尼、布里斯班共用同一会员价格和会员账号；切换城市只会改变你看到的本地福利与活动。</p></div><div class="membership"><div class="member-panel"><h3>候场会员 · Membership</h3><div class="price">A$12.80 <small>/ 月</small></div><div class="note">年付 A$99.80。两种方案适用于全部三个城市。</div><div class="benefit-list"><div>✓ 数字会员卡（无 QR Code）</div><div>✓ 所选城市的合作商家福利</div><div>✓ 所选城市的免费开放麦信息</div><div>✓ 所有城市的符合条件商演／专业演出均优惠 A$10 off</div></div><div class="field"><label for="member-city">选择你的常驻城市</label><select id="member-city"><option value="melbourne">墨尔本 Melbourne</option><option value="sydney">悉尼 Sydney</option><option value="brisbane">布里斯班 Brisbane</option></select></div><p class="note">城市选择目前为前端预览；接入会员登录后会保存到会员资料。真实付款和自动续费须待 Stripe 后端完成后启用。</p><a class="btn primary" href="#login">会员登录 / 加入会员</a><a class="btn" href="#benefits" style="margin-left:8px">查看城市福利</a></div><div class="digital-card"><img src="assets/logo.png"><div><div class="member-no">LOADING ZONE · MEMBER</div><div class="member-name">Your Name</div><div>MEMBERSHIP · CITY BASED BENEFITS</div><div>VALID UNTIL · —</div></div></div></div></section>`}
function benefits(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">MEMBER BENEFITS</div><h2>城市会员福利</h2></div><p>选择城市后查看当地合作商家福利。三个城市的符合条件商业／专业演出统一 A$10 off；免费开放麦目前仅墨尔本有，全部来自 Eventbrite。</p></div><div class="field" style="max-width:360px"><label for="benefit-city">选择城市 / Select city</label><select id="benefit-city"><option value="melbourne">墨尔本 Melbourne</option><option value="sydney">悉尼 Sydney</option><option value="brisbane">布里斯班 Brisbane</option></select></div><div id="city-benefit-content"></div><div class="benefits-grid" style="margin-top:22px"><div class="benefit-card"><div class="benefit-icon">01</div><h3>商家专属福利</h3><p>只展示所选城市已启用的合作商家、折扣内容和使用条件。</p></div><div class="benefit-card"><div class="benefit-icon">02</div><h3>免费开放麦</h3><p>按城市展示开放麦日期、场地、预约链接及名额信息。</p></div><div class="benefit-card"><div class="benefit-icon">03</div><h3>会员演出权益</h3><p>墨尔本、悉尼和布里斯班的符合条件商业／专业演出统一享 A$10 off，具体适用场次以活动条款为准。</p></div></div><p class="note" style="margin-top:18px">当前页面为城市切换 UI 预览；商家与活动数据将在安全后端和后台管理功能接通后动态显示。</p></section>`}
function login(){return `<section class="section"><div class="login"><div class="eyebrow">MEMBER AREA</div><h2>会员登录</h2><p class="meta">使用邮箱或手机号接收一次性验证码。</p><div class="field"><label>邮箱 / 手机号</label><input placeholder="you@example.com / 04xx xxx xxx"></div><button class="btn primary" onclick="toast('验证码发送功能将在正式后端接入')">发送验证码</button><p class="note">正式版将连接会员数据库，并在登录后显示数字会员卡、有效期与会员福利。</p></div></section>`}
function admin(){return `<section class="section"><div class="login" style="max-width:760px"><div class="eyebrow">ADMIN · LOADING ZONE</div><h2>后台管理员登录</h2><p class="meta">仅允许已配置的管理员邮箱访问会员折扣码导出。请使用管理员邮箱接收一次性验证码。</p><div class="field"><label for="admin-email">管理员邮箱</label><input id="admin-email" type="email" autocomplete="email" placeholder="admin@loadingzonecomedy.com"></div><button class="btn" id="admin-send-code" type="button">发送登录验证码</button><div class="field" style="margin-top:16px"><label for="admin-otp">邮箱验证码</label><input id="admin-otp" inputmode="numeric" autocomplete="one-time-code" placeholder="输入邮件中的验证码"></div><button class="btn primary" id="admin-verify-code" type="button">验证并登录</button><p id="admin-auth-message" class="note" role="status" aria-live="polite">尚未登录。会员折扣码导出需要服务器再次验证管理员权限。</p><div class="member-panel" style="margin-top:22px"><div class="eyebrow">MEMBER DISCOUNT CODES</div><h3>会员专属折扣码导出</h3><p class="note">仅导出有效会员及有效折扣码，供管理员在对应票务平台手动配置。此导出不会自动在 Eventbrite 或其他售票平台创建折扣码。</p><div class="cta-row"><button class="btn primary" id="admin-export-codes" type="button">导出有效会员 CSV</button><button class="btn" id="admin-sign-out" type="button">退出登录</button></div></div><p class="note" style="margin-top:18px">提示：如果验证码邮件未收到，请检查垃圾邮件文件夹。不要把验证码转发给他人。</p></div></section>`}
function wire(){const adminSend=document.getElementById('admin-send-code');if(adminSend)adminSend.onclick=adminSendCode;const adminVerify=document.getElementById('admin-verify-code');if(adminVerify)adminVerify.onclick=adminVerifyCode;const adminExport=document.getElementById('admin-export-codes');if(adminExport)adminExport.onclick=adminExportCodes;const adminOut=document.getElementById('admin-sign-out');if(adminOut)adminOut.onclick=adminSignOut;const adminEmail=document.getElementById('admin-email');if(adminEmail&&sessionStorage.getItem('lz_admin_user_email'))adminEmail.value=sessionStorage.getItem('lz_admin_user_email');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=copy[lang][e.dataset.i18n]);const b=document.getElementById('langBtn');if(b)b.onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('lz_lang',lang);render()};const sw=document.getElementById('renew');if(sw)sw.onclick=()=>sw.classList.toggle('on');const savedCity=localStorage.getItem('lz_member_city')||'melbourne';const memberCity=document.getElementById('member-city');const benefitCity=document.getElementById('benefit-city');if(memberCity){memberCity.value=savedCity;memberCity.onchange=()=>{localStorage.setItem('lz_member_city',memberCity.value)}}if(benefitCity){benefitCity.value=savedCity;benefitCity.onchange=()=>{localStorage.setItem('lz_member_city',benefitCity.value);renderCityBenefits(benefitCity.value)};renderCityBenefits(savedCity)}}

function adminMessage(message){const el=document.getElementById('admin-auth-message');if(el)el.textContent=message}
async function adminAuthConfig(){const r=await fetch('/api/admin/auth-config',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('管理员登录暂不可用');return r.json()}
async function adminSendCode(){
 const emailEl=document.getElementById('admin-email');const email=(emailEl?.value||'').trim().toLowerCase();
 if(!email||!email.includes('@')){adminMessage('请输入有效的管理员邮箱。');return}
 const send=document.getElementById('admin-send-code');if(send)send.disabled=true;
 try{const cfg=await adminAuthConfig();const r=await fetch(cfg.url.replace(/\/$/,'')+'/auth/v1/otp',{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.publishableKey},body:JSON.stringify({email,create_user:true})});if(!r.ok)throw new Error('无法发送验证码，请确认邮箱已在会员认证系统中注册并检查邮件设置。');sessionStorage.setItem('lz_admin_pending_email',email);adminMessage('如果该邮箱已注册且邮件服务正常，验证码将发送至该邮箱。请检查收件箱和垃圾邮件。')}catch(e){adminMessage(e.message||'验证码发送失败，请稍后再试。')}finally{if(send)send.disabled=false}
}
async function adminVerifyCode(){
 const email=sessionStorage.getItem('lz_admin_pending_email')||(document.getElementById('admin-email')?.value||'').trim().toLowerCase();const token=(document.getElementById('admin-otp')?.value||'').trim();
 if(!email||!token){adminMessage('请先发送验证码，再输入邮件中的验证码。');return}
 const btn=document.getElementById('admin-verify-code');if(btn)btn.disabled=true;
 try{const cfg=await adminAuthConfig();const r=await fetch(cfg.url.replace(/\/$/,'')+'/auth/v1/verify',{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.publishableKey},body:JSON.stringify({email,token,type:'email'})});if(!r.ok)throw new Error('验证码无效或已过期，请重新获取。');const data=await r.json();if(!data.access_token)throw new Error('认证服务未返回登录令牌。');sessionStorage.setItem('lz_admin_access_token',data.access_token);sessionStorage.setItem('lz_admin_user_email',email);adminMessage('邮箱验证成功。导出时服务器还会检查管理员邮箱白名单。')}catch(e){adminMessage(e.message||'登录失败，请重试。')}finally{if(btn)btn.disabled=false}
}
async function adminExportCodes(){
 const token=sessionStorage.getItem('lz_admin_access_token');if(!token){adminMessage('请先完成管理员邮箱验证。');return}
 const btn=document.getElementById('admin-export-codes');if(btn)btn.disabled=true;
 try{const r=await fetch('/api/admin/member-discount-codes.csv',{headers:{Authorization:'Bearer '+token,Accept:'text/csv, application/json'}});if(!r.ok){let message='导出失败。';try{const data=await r.json();if(r.status===403)message='该邮箱已验证，但没有管理员导出权限。';else if(r.status===401)message='登录已失效，请重新验证邮箱。';else message=data.error||message}catch{}if(r.status===401){sessionStorage.removeItem('lz_admin_access_token')}throw new Error(message)}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='loading-zone-member-discount-codes.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);adminMessage('CSV 已生成并下载。请仅将其用于配置已批准的票务折扣。')}catch(e){adminMessage(e.message||'导出失败，请稍后重试。')}finally{if(btn)btn.disabled=false}
}
function adminSignOut(){sessionStorage.removeItem('lz_admin_access_token');sessionStorage.removeItem('lz_admin_user_email');sessionStorage.removeItem('lz_admin_pending_email');const otp=document.getElementById('admin-otp');if(otp)otp.value='';adminMessage('已退出当前浏览器会话。')}

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeExternalUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
async function renderCityBenefits(city){
 const el=document.getElementById('city-benefit-content');if(!el)return;
 const labels={melbourne:'墨尔本 Melbourne',sydney:'悉尼 Sydney',brisbane:'布里斯班 Brisbane'};
 const cityName=labels[city]||labels.melbourne;
 el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><p class="note">正在加载当地会员福利…</p></div>`;
 try{
  const response=await fetch('/api/member-content?city='+encodeURIComponent(city),{headers:{Accept:'application/json'}});
  if(!response.ok)throw new Error('content unavailable');
  const data=await response.json();
  const partners=Array.isArray(data.partners)?data.partners:[];
  const events=Array.isArray(data.events)?data.events:[];
  const partnerCards=partners.map(p=>{
   const url=safeExternalUrl(p.website_url);
   return `<article class="benefit-card"><div class="eyebrow">${escapeHtml(p.category||'LOCAL PARTNER')}</div><h3>${escapeHtml(p.name)}</h3><h4>${escapeHtml(p.benefit_title)}</h4>${p.discount_text?`<p><strong>${escapeHtml(p.discount_text)}</strong></p>`:''}${p.benefit_description?`<p>${escapeHtml(p.benefit_description)}</p>`:''}${p.terms?`<p class="note">使用条件：${escapeHtml(p.terms)}</p>`:''}${url?`<a class="card-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">商家网站 ↗</a>`:''}</article>`;
  }).join('');
  const eventLabels={free_open_mic:'免费开放麦',commercial_show:'商业演出',professional_show:'专业演出',other:'会员活动'};
  const eventCards=events.map(e=>{
   const url=safeExternalUrl(e.booking_url);
   const date=e.starts_at?new Date(e.starts_at):null;
   const timeZones={melbourne:'Australia/Melbourne',sydney:'Australia/Sydney',brisbane:'Australia/Brisbane'};
   const dateText=date&&!Number.isNaN(date.getTime())?date.toLocaleString('zh-AU',{dateStyle:'medium',timeStyle:'short',timeZone:timeZones[city]||'Australia/Melbourne'}):'时间待公布';
   return `<article class="benefit-card"><div class="eyebrow">${escapeHtml(eventLabels[e.event_type]||'会员活动')}</div><h3>${escapeHtml(e.title)}</h3><p><strong>${escapeHtml(dateText)}</strong></p>${e.venue?`<p>${escapeHtml(e.venue)}</p>`:''}${e.description?`<p>${escapeHtml(e.description)}</p>`:''}${Number.isInteger(e.capacity)?`<p class="note">活动名额：${e.capacity}</p>`:''}${url?`<a class="card-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">活动 / 预约详情 ↗</a>`:''}</article>`;
  }).join('');
  el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><h3>合作商家福利</h3>${partners.length?`<div class="benefits-grid">${partnerCards}</div>`:'<p class="note">这个城市暂时还没有已发布的商家福利，后续添加并启用后会显示在这里。</p>'}<h3 style="margin-top:24px">免费开放麦与会员活动</h3>${events.length?`<div class="benefits-grid">${eventCards}</div>`:'<p class="note">这个城市暂时还没有已发布的活动，后续添加并启用后会显示在这里。</p>'}</div>`;
 }catch(_error){
  el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><p class="note">暂时无法加载城市权益。请稍后再试；目前不会用演示内容冒充真实福利。</p></div>`;
 }
}
function toast(t){const e=document.querySelector('.toast')||Object.assign(document.body.appendChild(document.createElement('div')),{className:'toast'});e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
window.addEventListener('hashchange',render);render();
