const gallery=['show-01.jpeg','show-02.jpeg','show-03.jpeg','show-04.jpeg','show-05.jpeg','show-06.jpeg','show-07.jpeg','show-08.jpeg','show-09.jpeg','show-10.jpeg'];
const copy={zh:{navShows:'近期演出',navGallery:'过往演出',navMembership:'会员',navBenefits:'会员福利',memberLogin:'会员登录'},en:{navShows:'Shows',navGallery:'Past Shows',navMembership:'Membership',navBenefits:'Benefits',memberLogin:'Member Login'}};
let lang=localStorage.getItem('lz_lang')||'zh';
function img(n){return 'assets/gallery/'+n}
function render(){const r=location.hash.replace('#','')||'home';const app=document.getElementById('app'); if(r==='home')app.innerHTML=home(); else if(r==='shows')app.innerHTML=shows(); else if(r==='gallery')app.innerHTML=galleryPage(); else if(r==='membership')app.innerHTML=membership(); else if(r==='benefits')app.innerHTML=benefits(); else if(r==='login')app.innerHTML=login(); else if(r==='admin')app.innerHTML=admin(); else app.innerHTML=home(); wire();}
function home(){return `<section class="hero"><div class="hero-bg" style="background-image:url('assets/hero-home.jpeg')"></div><div class="hero-content"><div class="eyebrow">LOADING ZONE COMEDY · MELBOURNE</div><h1>把好笑的事，<br><em>认真做。</em></h1><p>候场喜剧是一群在墨尔本做中文现场喜剧的人。来看演出，也来成为我们的会员。</p><div class="cta-row"><a class="btn primary" href="#shows">查看近期演出</a><a class="btn" href="#membership">加入会员</a></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">UPCOMING</div><h2>近期演出</h2></div><p>Eventbrite 活动可通过后台自动同步到这里；网站仍可独立编辑中文标题、置顶和首页展示。</p></div>${showCards()}</section><section class="section alt"><div class="section-head"><div><div class="eyebrow">MEMBERSHIP</div><h2>成为候场会员</h2></div><p>一次购买即可成为会员，也可以选择自动续费，让会员福利持续有效。</p></div><div class="membership"><div class="member-panel"><div class="eyebrow">LOADING ZONE MEMBER</div><h3>一张会员卡，<br>把好笑带回生活。</h3><div class="price">$— <small>/ 会员详情待定</small></div><div class="benefit-list"><div>✓ 演出会员专属优惠</div><div>✓ 合作商家福利</div><div>✓ 数字会员卡</div></div><a class="btn primary" href="#membership">查看会员方案</a></div><div class="digital-card"><img src="assets/logo.png"><div><div class="member-no">LZC · MEMBER 000001</div><div class="member-name">示例会员</div><div>ACTIVE MEMBER · 2027.10.08</div></div></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">PAST SHOWS</div><h2>过往演出</h2></div><a class="btn" href="#gallery">浏览 Gallery</a></div><div class="gallery">${gallery.slice(0,6).map((x,i)=>`<figure><img src="${img(x)}"><figcaption>候场喜剧 · Past Show ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div></section>`}
function showCards(){let arr=[['10 OCT','Eventbrite · 近期演出','Eventbrite 活动导入 · 日期 / 场地 / 票务以活动页为准','eventbrite'],['待添加','其他场地演出','后台手动添加 · 可填写票务链接、场地与中文介绍','manual'],['待添加','特别演出 / 联合演出','后台手动添加 · 可设置首页置顶与展示顺序','manual']];return `<div class="cards">${arr.map(s=>`<article class="show-card show-source-card"><div class="show-placeholder ${s[3]}"><span>${s[3]==='eventbrite'?'EVENTBRITE':'MANUAL'}</span></div><div class="show-body"><div class="date">${s[0]}</div><h3>${s[1]}</h3><div class="meta">${s[2]}</div><a class="card-link" href="#shows">查看详情 →</a></div></article>`).join('')}</div>`}
function shows(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">UPCOMING SHOWS</div><h2>近期演出</h2></div><p>Eventbrite 演出自动导入；其他场地或其他售票平台的演出可由后台手动添加。</p></div>${showCards()}</section>`}
function galleryPage(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">GALLERY</div><h2>过往演出</h2></div><p>这里专门展示过往演出照片。你提供的照片全部归入 Past Shows；以后可以继续从后台上传新照片、添加标题并发布。</p></div><div class="gallery">${gallery.map((x,i)=>`<figure><img src="${img(x)}"><figcaption>Past Show ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div></section>`}
function membership(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">MEMBERSHIP</div><h2>候场会员</h2></div><p>墨尔本、悉尼、布里斯班共用同一会员价格和会员账号；切换城市只会改变你看到的本地福利与活动。</p></div><div class="membership"><div class="member-panel"><h3>候场会员 · Membership</h3><div class="price">A$12.80 <small>/ 月</small></div><div class="note">年付 A$99.80。两种方案适用于全部三个城市。</div><div class="benefit-list"><div>✓ 数字会员卡（无 QR Code）</div><div>✓ 所选城市的合作商家福利</div><div>✓ 所选城市的免费开放麦信息</div><div>✓ 所有城市的符合条件商演／专业演出均优惠 A$10 off</div></div><div class="field"><label for="member-city">选择你的常驻城市</label><select id="member-city"><option value="melbourne">墨尔本 Melbourne</option><option value="sydney">悉尼 Sydney</option><option value="brisbane">布里斯班 Brisbane</option></select></div><p class="note">城市选择目前为前端预览；接入会员登录后会保存到会员资料。真实付款和自动续费须待 Stripe 后端完成后启用。</p><a class="btn primary" href="#login">会员登录 / 加入会员</a><a class="btn" href="#benefits" style="margin-left:8px">查看城市福利</a></div><div class="digital-card"><img src="assets/logo.png"><div><div class="member-no">LOADING ZONE · MEMBER</div><div class="member-name">Your Name</div><div>MEMBERSHIP · CITY BASED BENEFITS</div><div>VALID UNTIL · —</div></div></div></div></section>`}
function benefits(){return `<section class="section"><div class="section-head"><div><div class="eyebrow">MEMBER BENEFITS</div><h2>城市会员福利</h2></div><p>选择城市后查看当地合作商家福利。三个城市的符合条件商业／专业演出统一 A$10 off；免费开放麦目前仅墨尔本有，全部来自 Eventbrite。</p></div><div class="field" style="max-width:360px"><label for="benefit-city">选择城市 / Select city</label><select id="benefit-city"><option value="melbourne">墨尔本 Melbourne</option><option value="sydney">悉尼 Sydney</option><option value="brisbane">布里斯班 Brisbane</option></select></div><div id="city-benefit-content"></div><div class="benefits-grid" style="margin-top:22px"><div class="benefit-card"><div class="benefit-icon">01</div><h3>商家专属福利</h3><p>只展示所选城市已启用的合作商家、折扣内容和使用条件。</p></div><div class="benefit-card"><div class="benefit-icon">02</div><h3>免费开放麦</h3><p>按城市展示开放麦日期、场地、预约链接及名额信息。</p></div><div class="benefit-card"><div class="benefit-icon">03</div><h3>会员演出权益</h3><p>墨尔本、悉尼和布里斯班的符合条件商业／专业演出统一享 A$10 off，具体适用场次以活动条款为准。</p></div></div><p class="note" style="margin-top:18px">当前页面为城市切换 UI 预览；商家与活动数据将在安全后端和后台管理功能接通后动态显示。</p></section>`}
function login(){return `<section class="section"><div class="login"><div class="eyebrow">MEMBER AREA</div><h2>会员登录</h2><p class="meta">使用邮箱或手机号接收一次性验证码。</p><div class="field"><label>邮箱 / 手机号</label><input placeholder="you@example.com / 04xx xxx xxx"></div><button class="btn primary" onclick="toast('验证码发送功能将在正式后端接入')">发送验证码</button><p class="note">正式版将连接会员数据库，并在登录后显示数字会员卡、有效期与会员福利。</p></div></section>`}
function admin(){return `<section class="admin-wrap"><div class="admin-shell"><aside class="admin-side"><h3>候场后台</h3><a class="active">Dashboard</a><a>Shows</a><a>Gallery</a><a>Benefits</a><a>Partners</a><a>Members</a><a>Homepage</a><a>Content</a><a>Membership</a><a>Settings</a><a>Integrations</a></aside><div class="admin-main"><div class="eyebrow">ADMIN · LOADING ZONE</div><h2>后台总览</h2><div class="stat-grid"><div class="stat"><span>Upcoming Shows</span><b>Eventbrite + Manual</b></div><div class="stat"><span>Gallery Photos</span><b>10</b></div><div class="stat"><span>Active Members</span><b>—</b></div><div class="stat"><span>Eventbrite</span><b class="status">Connected</b></div></div><div class="integration"><div><strong>Eventbrite Integration</strong><div class="note">自动同步近期演出；同步后可在后台补充中文内容，不覆盖网站手动字段。</div></div><button class="btn" onclick="toast('Demo：这里将调用安全后端 Eventbrite API 同步')">SYNC NOW</button></div><div class="member-panel" style="margin-top:18px"><div class="eyebrow">SHOW SOURCES</div><h3>近期演出来源</h3><div class="benefit-list"><div>✓ Eventbrite：自动导入标题、日期、场地、图片、票务链接、状态</div><div>✓ 其他场地 / 售票平台：后台手动新增演出</div><div>✓ 两类演出统一进入 Upcoming Shows，可设置置顶、排序与首页展示</div><div>✓ 过往演出照片独立管理在 Past Shows Gallery</div></div><div class="cta-row"><button class="btn" onclick="toast('Demo：打开手动添加演出表单')">＋ 手动添加演出</button><button class="btn" onclick="toast('Demo：打开 Past Shows Gallery 管理')">管理过往照片</button></div></div><div class="table"><div class="tr head"><span>内容</span><span>来源</span><span>状态</span><span></span></div><div class="tr"><span>Upcoming Shows</span><span>Eventbrite</span><span class="status">Published</span><button class="btn" style="padding:6px 10px">编辑</button></div><div class="tr"><span>Past Shows Gallery</span><span>Manual Upload</span><span class="status">Published</span><button class="btn" style="padding:6px 10px">管理</button></div><div class="tr"><span>Membership</span><span>CMS</span><span class="status">Draft</span><button class="btn" style="padding:6px 10px">设置</button></div></div><div class="member-panel" style="margin-top:18px"><div class="eyebrow">MEMBERSHIP SETTINGS</div><h3>一次性购买 + 自动续费可选</h3><p class="note">价格、周期、福利、续费规则全部可后台编辑。支付生产环境接入 Stripe 后启用真实付款。</p><div class="cta-row"><a class="btn primary" href="#membership">预览会员页面</a><button class="btn" onclick="toast('Demo：会员设置已保存')">保存设置</button></div></div></div></div></section>`}
function wire(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=copy[lang][e.dataset.i18n]);const b=document.getElementById('langBtn');if(b)b.onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('lz_lang',lang);render()};const sw=document.getElementById('renew');if(sw)sw.onclick=()=>sw.classList.toggle('on');const savedCity=localStorage.getItem('lz_member_city')||'melbourne';const memberCity=document.getElementById('member-city');const benefitCity=document.getElementById('benefit-city');if(memberCity){memberCity.value=savedCity;memberCity.onchange=()=>{localStorage.setItem('lz_member_city',memberCity.value)}}if(benefitCity){benefitCity.value=savedCity;benefitCity.onchange=()=>{localStorage.setItem('lz_member_city',benefitCity.value);renderCityBenefits(benefitCity.value)};renderCityBenefits(savedCity)}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeExternalUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
async function renderCityBenefits(city){
 const el=document.getElementById('city-benefit-content');if(!el)return;
 const labels={melbourne:'墨尔本 Melbourne',sydney:'悉尼 Sydney',brisbane:'布里斯班 Brisbane'};
 const cityName=labels[city]||labels.melbourne;
 el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><p class="note">正在加载当地会员福利…</p></div>`;
 try{
  const response=await fetch('/api/member-content?city='+encodeURIComponent(city),{headers:{Accept:'application/json'}});
  if(!response.ok)throw new Error('content unavailable');
  const data=await response.json();
  const partners=Array.isArray(data.partners)?data.partners:[];
  const events=Array.isArray(data.events)?data.events:[];
  const partnerCards=partners.map(p=>{
   const url=safeExternalUrl(p.website_url);
   return `<article class="benefit-card"><div class="eyebrow">${escapeHtml(p.category||'LOCAL PARTNER')}</div><h3>${escapeHtml(p.name)}</h3><h4>${escapeHtml(p.benefit_title)}</h4>${p.discount_text?`<p><strong>${escapeHtml(p.discount_text)}</strong></p>`:''}${p.benefit_description?`<p>${escapeHtml(p.benefit_description)}</p>`:''}${p.terms?`<p class="note">使用条件：${escapeHtml(p.terms)}</p>`:''}${url?`<a class="card-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">商家网站 ↗</a>`:''}</article>`;
  }).join('');
  const eventLabels={free_open_mic:'免费开放麦',commercial_show:'商业演出',professional_show:'专业演出',other:'会员活动'};
  const eventCards=events.map(e=>{
   const url=safeExternalUrl(e.booking_url);
   const date=e.starts_at?new Date(e.starts_at):null;
   const timeZones={melbourne:'Australia/Melbourne',sydney:'Australia/Sydney',brisbane:'Australia/Brisbane'};
   const dateText=date&&!Number.isNaN(date.getTime())?date.toLocaleString('zh-AU',{dateStyle:'medium',timeStyle:'short',timeZone:timeZones[city]||'Australia/Melbourne'}):'时间待公布';
   return `<article class="benefit-card"><div class="eyebrow">${escapeHtml(eventLabels[e.event_type]||'会员活动')}</div><h3>${escapeHtml(e.title)}</h3><p><strong>${escapeHtml(dateText)}</strong></p>${e.venue?`<p>${escapeHtml(e.venue)}</p>`:''}${e.description?`<p>${escapeHtml(e.description)}</p>`:''}${Number.isInteger(e.capacity)?`<p class="note">活动名额：${e.capacity}</p>`:''}${url?`<a class="card-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">活动 / 预约详情 ↗</a>`:''}</article>`;
  }).join('');
  el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><h3>合作商家福利</h3>${partners.length?`<div class="benefits-grid">${partnerCards}</div>`:'<p class="note">这个城市暂时还没有已发布的商家福利，后续添加并启用后会显示在这里。</p>'}<h3 style="margin-top:24px">免费开放麦与会员活动</h3>${events.length?`<div class="benefits-grid">${eventCards}</div>`:'<p class="note">这个城市暂时还没有已发布的活动，后续添加并启用后会显示在这里。</p>'}</div>`;
 }catch(_error){
  el.innerHTML=`<div class="member-panel" style="margin-top:18px"><div class="eyebrow">SELECTED CITY</div><h3>${escapeHtml(cityName)}</h3><p class="note">暂时无法加载城市权益。请稍后再试；目前不会用演示内容冒充真实福利。</p></div>`;
 }
}
function toast(t){const e=document.querySelector('.toast')||Object.assign(document.body.appendChild(document.createElement('div')),{className:'toast'});e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
window.addEventListener('hashchange',render);render();
